export type EmbeddingModel = string;

export type CreateEmbeddingInput =
  | string
  | Array<string>
  | Array<number>
  | Array<Array<number>>;

export type EmbeddingCreateParamsInput = CreateEmbeddingInput;

export interface EmbeddingCreateParams {
  /**
   * Input text to embed, encoded as a string or array of tokens.
   */
  input: EmbeddingCreateParamsInput;
  /**
   * ID of the model to use.
   */
  model: (string & {}) | EmbeddingModel;
  /**
   * The number of dimensions the resulting output embeddings should have.
   * Only supported in text-embedding-3 and later models.
   */
  dimensions?: number;
  /**
   * The format to return the embeddings in.
   */
  encoding_format?: "float" | "base64";
  /**
   * A unique identifier representing your end-user.
   */
  user?: string;
}

// Backward-compatible alias
export type CreateEmbeddingRequest = EmbeddingCreateParams;

export interface Embedding {
  /**
   * The embedding vector, which is a list of floats.
   */
  embedding: number[];
  /**
   * The index of the embedding in the list of embeddings.
   */
  index: number;
  /**
   * The object type, always "embedding".
   */
  object: "embedding";
}

export interface EmbeddingUsage {
  /**
   * The number of tokens used by the prompt.
   */
  prompt_tokens: number;
  /**
   * The total number of tokens used by the request.
   */
  total_tokens: number;
}

export interface CreateEmbeddingResponse {
  /**
   * The list of embeddings generated by the model.
   */
  data: Embedding[];
  /**
   * The name of the model used to generate the embedding.
   */
  model: string;
  /**
   * The object type, always "list".
   */
  object: "list";
  /**
   * The usage information for the request.
   */
  usage: CreateEmbeddingResponse.Usage;
}

export declare namespace CreateEmbeddingResponse {
  export interface Usage extends EmbeddingUsage {}
}
